### ISSUE TITLE
Add adapter tuning  strategy to the `Trainer`

### ISSUE THREAD

**Issue by arxyzan** [hezarai/hezar#115]
Can we add LoRa finetuning strategy to the Trainer?

**Comment by Adversarian** [comment]
It's possible to wrap the `Trainer` inside an [`OpenDelta`](https://github.com/thunlp/OpenDelta) (or a similar library) instance and then expose a couple of PEFT methods that way. I assume this might require handcrafting configs on a per-model and per-PEFT-method basis but it's certainly doable!

**Comment by arxyzan** [comment]
Thanks @Adversarian for the suggestion. As far as I remember, I dived deep into the HF PEFT library and it seemed like that we can add this feature with minimal effort thanks to the abstractions made in that library. But most of the overhead would be on the Hezar's side I think. Since adapters are separate parts appended to the model's architecture. I didn't have time to look into it since it was not urgent in that time and, current models in Hezar can be easily finetuned on consumer hardware. 
But in fact, we have some ongoing projects regarding larger models so that it's helpful to implement this feature too. 
Let me know what you think Arian jan!

**Comment by Adversarian** [comment]
No problem @arxyzan , it's my pleasure :).
I was going to point out the redundancy of adding PEFTs for smaller models since, if I remember correctly, it's been shown that PEFT-ing small models yields negligible gains at best and can have adverse effects on the performance at worst. However, I figured what you've built so far is a segue into LLM territory and it'd be nice to have things set-up and ready to go for when that happens. I'm a bit tied up at the moment but I will try to look further into this when I have some time.

**Comment by arxyzan** [comment]
Thanks @Adversarian , you're absolutely right. Adding PEFT for our current models might not seem to bring huge benefits but it'd be wisse to keep it in the schedule for the upcoming LLMs that are going to be added. So take your time since this is not urgent.

**Comment by arxyzan** [comment]
This is not a priority for now.
