### ISSUE TITLE
Weight conversion to `safetensors` format

### ISSUE THREAD

**Issue by Adversarian** [hezarai/hezar#153]
In the wake of security concerns associated with the `pickle` module (see [this](https://github.com/pytorch/pytorch/issues/52596)), almost all of the new entries at HF are in the new `safetensors` format which seems to be becoming the de facto replacement for `pickle` at this rate (see [this](https://huggingface.co/CohereForAI/c4ai-command-r-plus/tree/main) by Cohere for instance). Not only has it been shown that unlike `pickle`, arbitrary code execution is impossible through `safetensors`, `safetensors` also reduces potential RAM usage for bigger models through sharding and it demonstrates a loading speed-up of up to [2x on GPU and up to 76.6x on CPU](https://huggingface.co/docs/safetensors/speed).

I would like to propose a simple solution that allows you to serve your trained models on HF using the new `safetensors` format. The official `safetensors` HF page has a [space](https://huggingface.co/spaces/safetensors/convert) that allows for very simple conversion of already existing models. This page, although very streamlined, has the drawback that existing model weights need to follow a certain naming convention (`pytorch_model.bin` or `pytorch_model-xxxx-of-xxxx.bin`). 

Moreover, for offline conversion and a more customizable approach, I can refer you to [a script from the text-generation-webui repository](https://github.com/oobabooga/text-generation-webui/blob/main/convert-to-safetensors.py) which is an actively maintained repository, and [this](https://github.com/Silver267/pytorch-to-safetensor-converter/blob/main/convert_to_safetensor.py).

I understand that this may not be a priority at this time and I can potentially volunteer a PR myself later when I find some free time if this pitch sounds reasonable to you.

I'd like to close this out by thanking you for your tremendous work on advancing Persian NLP and saving countless hours of research time.

**Comment by arxyzan** [comment]
Hi @Adversarian, thanks a lot for the suggestion.
Actually, I worked on this a while back. As a first step, I tried to provide `safetensors` format for our current weights alongside the old `.pt` weights for the same reasons you mentioned, but unfortunately I ran into some errors when trying to convert Hezar Model instances to safetensors format. I don't actually remember what the error was but I'm pretty sure I put a good amount of time into it. The thing is that Hezar Model classes are regular PyTorch `nn.Module` subclasses which must be (in theory) easily serialized using safetensors so I do know that it's definitely possible. If you're willing to help I'm down to start this task again. Since it's pretty straightforward to test it out, I'd be glad if you could try it on a few of our models and share the results.

Best,
Aryan

**Comment by Adversarian** [comment]
I'm afraid you were right, since `hezar` doesn't piggyback on HF for model save/load utilities, adding `safetensors` support is not trivial and requires a fair bit of alteration to the codebase. I strongly recommend sub-classing HF's AutoModel classes to minimize technical debt and facilitate further development efforts in the future. However, I'm working on a quick-and-dirty proof of concept PR which I will submit as soon as I have a MWE.
