### ISSUE TITLE
How to using this project in subtitle edit?

### ISSUE THREAD

**Issue by Daredevil74** [hezarai/hezar#155]
Can amateur users who do not know anything about programming use this project? How can it be used in the subtitle edit program?

**Comment by arxyzan** [comment]
@Daredevil74 Hi, can you please provide a thorough description of the issue/feature ? What do you mean by subtitle edit?

**Comment by arxyzan** [comment]
@Daredevil74 sorry I still don't quite understand you needs. This project is an AI library and requires a basic knowledge of programming and AI but it's quite simple to work with overall. Can you please demonstrate your scenario and the desired input/output ?

**Comment by arxyzan** [comment]
@Daredevil74 I see, you need the OCR model. Unfortunately, we don't currently have a service for general use so that typical users can use it too. What you are currently using seems to be Tesseract. If you could setup a python environment on your local machine, the rest is pretty straightforward. Let me know what you plan to do.

**Comment by arxyzan** [comment]
@arxyzan I get it. Unfortunately, I don't think that Hezar can be integrated in the mentioned project. I don't exactly know what your workflow is but I think if You have the subtitle image files in a folder, etc. you can actually use Hezar to run the OCR model on them and get the results.

**Comment by arxyzan** [comment]
@Daredevil74 Well this is really cool. We are currently working to add a serving module to Hezar so that it can be deployed easier and later on, we'll have our own web service that is easily accessible for most users, but for now, the only option is to use Hezar as a Python package. 
One easy solution is to use Google Colab which has Python installed. Let me know if you have proper access to this service (and the data can be uploaded there or on your Google Drive) and I'll tell you where to go from there.
