### ISSUE TITLE
Make dependecies optional

### ISSUE THREAD

**Issue by likecodingloveproblems** [hezarai/hezar#168]
Hi, thanks for the great library

It's very heavy when installing, isn't it possible to make third party dependencies like nvidia cuda related ones optional, I mean some thing like `pip install hezar[cude]`?

**Comment by arxyzan** [comment]
@likecodingloveproblems Hi what's up.
In fact the base dependencies are not that much:
```
torch
omegaconf
transformers
tokenizers
datasets
huggingface_hub
tensorboard
scikit-learn
accelerate
```
But these libraries themselves have a lot of dependencies and mostly (as you mentioned) is because of `torch` that requires a lot of libs and binaries for CUDA. I think that if you already have the CPU version of torch, hezar's installation will skip all that CUDA related packages. I'm not sure though!
