### ISSUE TITLE
Move hezar's cache directory to .cache instead of .hezarai in home directory

### ISSUE THREAD

**Issue by pooya-mohammadi** [hezarai/hezar#88]

**Comment by arxyzan** [comment]
I think about this every once in a while. 
The downside of `.cache ` is that most cleanup softwares and scripts delete it completely which is not desired since our cache can go above Gigabytes of space and no one would want to redownload everything over and over. 
On the other hand, the home directory hidden folders are usually used for the main apps like .nv, .mozilla, etc. So having `.hezar` folder in the home dir messes up the view even though it's hidden.

I'm down with changing the path to somewhere inside `.cache` but this would be a backward incompatible change.

**Comment by arxyzan** [comment]
Done in af49c2d
